### ISSUE TITLE
Wrong assumptions checking for resolution

### ISSUE THREAD

**Issue by toyg** [ShiKu123/Wallpaper-Sanitiser-#1]
This is a nice project, definitely useful, but the algorithm you use to determine whether to keep a file or not is just wrong.

Say your target res is 1920 x 1080, and you have a file that is 2000 x 1040; it passes your check, but it's not tall enough. Same if you get something that is 1900 x 10000: not wide enough. You really have to check both values and approve only if they are both right.

**Comment by acwyk** [comment]
Thanks for the feedback and looking at my project. I will be sure to fix this issue. Again, thank you for looking at my project, and feel free to add to it if you like.

I think the issue should be fixed now. I'd appreciate any additional comments or issues.
